version: "3.9"
services:

  node-application:
    build: .
    container_name: node-application
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    working_dir: /app
    command: "npm run dev"
    ports:
      - "3000:3000"
      - "9229:9229"
  nodedebug-postgres:
    image: postgres:18.3-alpine
    container_name: nodedebug-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
